# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase실습(장인수님)' do
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase실습(장인수님)

end
